# Use the official OpenJDK image from Docker Hub as the base image
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file generated by Maven into the container
COPY target/codechecker-0.0.1-SNAPSHOT.jar /app/codechecker.jar

# Expose the port that Spring Boot will run on (8080 is default)
EXPOSE 8080

# Command to run the Spring Boot app when the container starts
CMD ["java", "-jar", "codechecker.jar"]
